# Custom Language File for Launcher Customizer

[ejs.app]
title = "태초마을"

[ejs.landing]
mediaGitHubURL = "https://github.com/go-tiger/Taecho-Village"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/go-tiger/Taecho-Village"
supportLink = "https://github.com/go-tiger/Taecho-Village/issues"

[ejs.welcome]
welcomeHeader = "태초마을에 오신 것을 환영합니다"